### ISSUE TITLE
Partner logos should be updated

### ISSUE THREAD

**Issue by stakats** [tropy/tropy.github.io#24]
We need Mellon's new branding, and C²DH should switch places with RRCHNM

**Comment by flachware** [comment]
Is this the logo variant we should use?

![mellon-logo](https://user-images.githubusercontent.com/419747/178714107-135a09ad-24d8-4621-a6c6-880d82fb5f09.svg)

**Comment by stakats** [comment]
Yes, that's it.

**Comment by flachware** [comment]
Ok.
